on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: "write"
  pages: "write"
  id-token: "write"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:

    runs-on: "ubuntu-latest"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      # Prepare
      - uses: "actions/checkout@v5"
        with:
          lfs: "true"
      - run: "pip install poetry"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: "poetry install"

      # Build
      - run: "echo 'YACV_DISABLE_SERVER=True' >> $GITHUB_ENV"
      #- run: "poetry run python src/conn_grid.py"
      #- run: "poetry run python src/screwable_cylinder.py"
      - run: "poetry run python src/core.py"
      - run: "poetry run python src/module_allen_box.py"
      - run: "cp assets/*.glb export/"

      # Deploy
      - uses: "actions/configure-pages@v5"
      - uses: "actions/upload-pages-artifact@v4"
        with:
          path: 'export'
      - id: "deployment"
        uses: "actions/deploy-pages@v4"

      # If release...
      #- run: 'zip -r exports.zip export'
      #- uses: "svenstaro/upload-release-action@v2"
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    file: "exports.zip"
      #    tag: "${{ github.ref }}"
      #    overwrite: true

