on:
  push:
    branches: [ "main" ]
  workflow_dispatch: { }

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: "write"
  pages: "write"
  id-token: "write"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:

    runs-on: "ubuntu-latest"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      # Prepare
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
          cache: "pip"
      - run: "pip install -r requirements.txt"

      # Build
      - run: "echo 'YACV_DISABLE_SERVER = True' >> $GITHUB_ENV"
      - run: "python src/conn_grid.py"
      - run: "python src/screwable_cylinder.py"
      - run: "python src/core.py"
      - run: "python src/module_allen_box.py"

      # Deploy
      - uses: "actions/configure-pages@v4"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: 'export'
      - id: "deployment"
        uses: "actions/deploy-pages@v4"

      # If release...
#      - run: 'zip -r exports.zip export'
#      - uses: "svenstaro/upload-release-action@v2"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          file: "exports.zip"
#          tag: "${{ github.ref }}"
#          overwrite: true

